package com.example.productapi.service;
import com.example.productapi.dto.AuthDtos.*; import com.example.productapi.entity.*; import com.example.productapi.repository.*; import com.example.productapi.security.JwtService; import org.springframework.security.authentication.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.security.SecureRandom; import java.time.Instant; import java.util.Base64;  import java.util.UUID;
@Service public class AuthService {
 private final UserRepository users; private final RefreshTokenRepository refresh; private final PasswordEncoder encoder; private final AuthenticationManager auth; private final JwtService jwt; private final SecureRandom random=new SecureRandom();
 public AuthService(UserRepository u,RefreshTokenRepository r,PasswordEncoder e,AuthenticationManager a,JwtService j){users=u;refresh=r;encoder=e;auth=a;jwt=j;}
 @Transactional public void register(RegisterRequest req){if(users.findByUsername(req.username()).isPresent())throw new IllegalArgumentException("Username already exists");users.save(new AppUser(req.username(),encoder.encode(req.password()),Role.USER));}
 @Transactional public TokenResponse login(LoginRequest req){auth.authenticate(new UsernamePasswordAuthenticationToken(req.username(),req.password()));return issue(users.findByUsername(req.username()).orElseThrow());}
 @Transactional public TokenResponse rotate(RefreshRequest req){var old=refresh.findByTokenHash(hash(req.refreshToken())).orElseThrow(()->new IllegalArgumentException("Invalid refresh token"));if(old.isRevoked()||old.getExpiresAt().isBefore(Instant.now()))throw new IllegalArgumentException("Refresh token expired or revoked");old.setRevoked(true);refresh.save(old);return issue(old.getUser());}
 private TokenResponse issue(AppUser u){String access=jwt.generateAccessToken(u.getUsername(),u.getRole().name());String raw=randomToken();var rt=new RefreshToken();rt.setTokenHash(hash(raw));rt.setUser(u);rt.setExpiresAt(Instant.now().plusSeconds(7*24*3600));rt.setRevoked(false);rt.setFamilyId(UUID.randomUUID().toString());refresh.save(rt);return new TokenResponse(access,raw,"Bearer",jwt.getAccessSeconds());}
 private String randomToken(){byte[] b=new byte[48];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String s){try{return Base64.getUrlEncoder().withoutPadding().encodeToString(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
